name: Check

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: ['main']
    types: [ labeled, synchronize ]

jobs:
  check:
    if: github.event.label.name == 'run-checks'
    runs-on: ubuntu-latest
    name: Run Check

    steps:
      - uses: actions/checkout@v4

      - name: 'Use Node 20.11.1'
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

  delete-labels:
    needs: check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Delete label
        if: contains(github.event.pull_request.labels.*.name, 'run-checks')
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ['run-checks']
              });
              console.log("Label removed successfully");
            } catch (error) {
              console.log("Error removing label");
            }