name: Create PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    name: Create Pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create PR to main
        run: |
          gh pr create -H alex/pr -B main -t "Automated PR" -b "Create auto PR and run checks"
          gh pr merge --auto -s -d
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Empty Commit
        run: |
          git checkout alex/pr
          git commit --allow-empty -m "Trigger Checks"
          git push origin alex/pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}