name: Create PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    name: Create Pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git user for commits
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Empty Commit and PR
        run: |
          git commit --allow-empty -m "Trigger Checks"
          git push origin alex/pr
          gh pr create -H alex/pr -B main -t "Automated PR" -b "Create auto PR and run checks"
          gh pr merge --auto -s -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create non-empty commit
        run: |
          echo "This is a non-empty commit" > non_empty_file.txt
          git add non_empty_file.txt
          git commit -m "Add non-empty commit"
          git push origin alex/pr