name: Run Checks

on:
  pull_request:
    types: [ labeled ]

jobs:
  trigger-pr-check:
    if: github.event.label.name == 'run-checks'
    name: Trigger PR Check Workflow
    uses: ./.github/workflows/check.yml