name: Run Checks

on:
  pull_request:
    types: [ labeled ]

jobs:
  trigger-pr-check:
    if: github.event.label.name == 'reusable-label'
    name: Trigger PR Check Workflow
    uses: ./.github/workflows/check.yml

  delete-labels:
    needs: trigger-pr-check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Delete label
        if: contains(github.event.pull_request.labels.*.name, 'reusable-label')
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['reusable-label']
            })